name: rick_and_morty
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^15.1.1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  logger: ^2.5.0
  pretty_dio_logger: ^1.4.0
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.1.0
  dyn_mouse_scroll: ^1.0.7
  smooth_scroll_multiplatform: ^1.0.8
  skeletonizer: ^1.4.3
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.9
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  flutter_gen_runner: ^5.10.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true



  assets:
    - assets/images/
  
